### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by DresdenNight** [jmb05/BetterWeapons#1]
Doesn't support fabric 1.20 idw why

**Comment by jmb05** [comment]
Could you provide more context?  Maybe you could provide a log-file. Have you added Better Combat and its dependencies.

**Comment by DresdenNight** [comment]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'BetterWeapons' (betterweapons) 1.0.0 with any version that is compatible with:
		 - minecraft 1.20
Unmet dependency listing:
	 - Mod 'BetterWeapons' (betterweapons) 1.0.0 requires any version between 1.20.1 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)


And yes, I've installed Better Combat-fabric-1.7.2+1.20.1

**Comment by jmb05** [comment]
The Mod currently requires Minecraft 1.20.1 you are still running 1.20. You should consider updating, its only a bug-fixing update. But if you that is not an option for you I could include support for 1.20.

**Comment by DresdenNight** [comment]
Sure.Thank you very much

**Comment by jmb05** [comment]
Fixed in 1.0.1
